# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause

name: Docker Build
run-name: ${{ github.actor }} is building docker images
on:
  push:
    branches:
      - main
      - github-workflows

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out Github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Docker build and push all platforms
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/riscv64
          push: true
          tags: xronosinc/lf:unstable
